# Generated by Django 5.1.3 on 2025-02-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_chat_user_alter_user_distance_alter_user_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stops',
            field=models.JSONField(null=True),
        ),
    ]
